# Generated by Django 3.0.7 on 2020-06-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mob',
            field=models.CharField(max_length=10),
        ),
    ]
